import type { Metadata } from "next";
import "./globals.css";
import NavbarTop from "@/app/components/navbarTop";
import Footer from "@/app/components/footer";




export const metadata: Metadata = {
  title: "Hackathon Project",
  description: "Generated by Masood Noor",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={` antialiased `  }>
        <NavbarTop />
        {children}
        <Footer />
      </body>
    </html>
  );
}
